# Generated by Django 3.1 on 2020-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('blood', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('mandal', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
            ],
        ),
    ]
